### ISSUE TITLE
Boleto Santander

### ISSUE THREAD

**Issue by juancpgo** [tomas-stefano/boleto_bancario#10]
Olá.. Estou fazendo um sistema Rails. Gostaria de saber se alguém tem usado esta gem para boletos Santander. Só pra confirmar se está funcionando OK. Obg :)

**Comment by tomas-stefano** [comment]
Sim, tem algumas empresas usando Santander. Uma delas se chama Olook. Embora tenha um PR sobre o Santander aberto, ela está funcionando 'OK' com o que está implementado hoje, tanto na master branch como na versão mais atual. Mas caso você ache alguma coisa ou tenha homologado algum banco, fique a vontade de abrir um PR. Sobre a gem, coloquei todas as informações no Readme, caso tenha mais alguma dúvida. Abraços :)
